// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hiwktdvoqrftaquczjlu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhpd2t0ZHZvcXJmdGFxdWN6amx1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk3NDI5MTksImV4cCI6MjA4NTMxODkxOX0.Vc1KdblJpneTWRxYFEvEfw9AHnDIb-MTilA9imokWOY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});